version: 0.1

phases:
  build:
    commands:
      - docker build -t ml-test-repo .

  post_build:
    commands:
      - eval `aws ecr get-login --region us-east-1`
      - docker tag ml-test-repo:latest <your account number>.dkr.ecr.us-east-1.amazonaws.com/ml-test-repo:latest
      - docker push <your account number>.dkr.ecr.us-east-1.amazonaws.com/ml-test-repo:latest
