version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 18

  build:
    commands:
      - docker build -t ml-test-repo .

  post_build:
    commands:
      - eval `aws ecr get-login --region ap-southeast-2 --no-include-email`
      - docker tag ml-test-repo:latest $(aws sts get-caller-identity --output text --query 'Account').dkr.ecr.ap-southeast-2.amazonaws.com/ml-test-repo:latest
      - docker push $(aws sts get-caller-identity --output text --query 'Account').dkr.ecr.ap-southeast-2.amazonaws.com/ml-test-repo:latest
