version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - docker build -t ml-test-repo .

  post_build:
    commands:
      - eval `aws ecr get-login --region ap-southeast-2`
      - docker tag ml-test-repo:latest <your account number>.dkr.ecr.ap-southeast-2.amazonaws.com/ml-test-repo:latest
      - docker push <your account number>.dkr.ecr.ap-southeast-2.amazonaws.com/ml-test-repo:latest
